export const NUMBER_OF_EMPTY_ROWS_FOR_MANUAL_DATA_INPUT = 100;

export const NUMBER_OF_EXAMPLES_IN_MAPPING = 3;

export const SUPPORTED_FILE_MIME_TYPES = ['text/csv'];

export const DOWNLOADED_CSV_SEPARATOR = ',';
